---
## Controls Files. 
# These are YAML files that hold all the details for running checks.
#
## Uncomment to use different control file paths.
# masterControls: $HOME/.cis_kubernetes/master.yaml
# nodeControls: $HOME/.cis_kubernetes/node.yaml
# federatedControls: $HOME/.cis_kubernetes/federated.yaml

## Configuration Directories.
# Specifies the directories to look for configuration files
# for the kubernetes components.
#
## Uncomment to use different paths.
# kubeConfDir: /etc/kubernetes
# etcdConfDir: /etc/etcd
# flanneldConfDir: /etc/sysconfig
