---
## Controls Files. 
# These are YAML files that hold all the details for running checks.
#
## Uncomment to use different control file paths.
# masterControls: ./cfg/master.yaml
# nodeControls: ./cfg/node.yaml
# federatedControls: ./cfg/federated.yaml

master:
  bins: 
    apiserver:
      - "kube-apiserver"
      - "hyperkube apiserver"
      - "apiserver"
    scheduler:
      - "kube-scheduler"
      - "hyperkube scheduler"
      - "scheduler"
    controllermanager:
      - "kube-controller-manager"
      - "hyperkube controller-manager"
      - "controller-manager"
  confs:
    apiserver: 
      - /etc/kubernetes/admin.conf
      - /etc/kubernetes/apiserver
      - /etc/kubernetes/manifests/kube-apiserver.yaml
    scheduler: 
      - /etc/kubernetes/scheduler.conf
      - /etc/kubernetes/scheduler
      - /etc/kubernetes/manifests/kube-scheduler.yaml
    controller-manager: 
      - /etc/kubernetes/controller-manager.conf
      - /etc/kubernetes/controller-manager
      - /etc/kubernetes/manifests/kube-controller-manager.yaml
    etcd:
      - /etc/etcd/etcd.conf
    flanneld:
      - /etc/sysconfig/flanneld

node:
  bins:
    kubelet:
      - "hyperkube kubelet"
      - "kubelet"
    proxy:
      - "kube-proxy"
      - "hyperkube proxy"
      - "proxy"
  confs:
    kubelet: 
      - /etc/kubernetes/kubelet.conf
      - /etc/kubernetes/kubelet
    proxy: 
      - /etc/kubernetes/proxy.conf
      - /etc/kubernetes/proxy
      - /etc/kubernetes/addons/kube-proxy-daemonset.yaml

federated:
  bins:
    fedapiserver:
      - "hyperkube federation-apiserver"
      - "kube-federation-apiserver"
      - "federation-apiserver"
    fedcontrollermanager:
      - "hyperkube federation-controller-manager"
      - "kube-federation-controller-manager"
      - "federation-controller-manager"

optional:
  bins:
    etcd:
      - "etcd"
    flanneld:
      - "flanneld"
