---
## Controls Files.
# These are YAML files that hold all the details for running checks.
#
## Uncomment to use different control file paths.
# masterControls: ./cfg/master.yaml
# nodeControls: ./cfg/node.yaml
# federatedControls: ./cfg/federated.yaml

master:
  apiserver:
    bins:
      - openshift start master api

  scheduler:
    bins:
      - openshift start master controllers

  controllermanager:
    bins:
      - openshift start master controllers

node:
  kubelet:
    bins:
      - openshift start network

  proxy:
    bins:
      - openshift start network
