---
## Version-specific settings that override the values in cfg/config.yaml

master:
  apiserver:
    bins:
      - hypershift openshift-kube-apiserver

  etcd:
    bins:
      - openshift start etcd

node:
  proxy:
    bins:
      - openshift start network
